package com.sgai.cxmc.service.impl;

import com.sgai.cxmc.service.QueryDataService;
import com.sgai.cxmc.service.ShebeiService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

/**
 * @Description:
 * @Author: 李锐平
 * @Date: 2019/8/24 10:03
 * @Version 1.0
 */

@Service("shebeiServiceQs")
public class ShebeiServiceQsImpl implements ShebeiService {
    @Autowired
    QueryDataService queryDataService;
    @Autowired
    JdbcTemplate jdbcTemplate;

    @Override
    public Object zlGlyljtjsj() {
        String sql = "select to_char(sysdate - 1, 'yyyy-mm') calendar, t.department_name, sum(STOP_HOURS) stop_hours\n"
                + " from sgmc.V_MC_ZB_EM_LJTJ t\n"
                + " where t.STOP_BEGIN_D >= to_char(sysdate - 1, 'yyyy-mm')\n"
                + " group by t.department_name\n"
                + " order by stop_hours ";
        return queryDataService.query(sql);
    }

    @Override
    public Object zlTjsjqsd(String typeName) {
        String sql = "select * "
                + " from (select decode(department_name, '顺冷', '顺义冷轧', department_name)as department_name, calendar, stop_hours\n"
                + "      from (SELECT t.DEPARTMENT_NAME, substr(t.STOP_END_D, 1, 10) calendar, sum(t.STOP_HOURS) stop_hours\n"
                + "            FROM SGMC.V_MC_ZB_EM_LJTJ t\n"
                + "            group by t.DEPARTMENT_NAME, substr(t.STOP_END_D, 1, 10)\n"
                + "            order by substr(t.STOP_END_D, 1, 10))\n"
                + "      where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "        and calendar >= to_char(current date - 30, 'yyyy-mm-dd'))\n"
                + " where department_name = '"+typeName+"' "
                + " order by calendar";
        return queryDataService.query(sql);
    }

    @Override
    public Object zlTjsjqsm(String typeName) {
        String sql = "select * "
                + " from (select decode(department_name, '顺冷', '顺义冷轧', department_name)as department_name, calendar, stop_hours\n"
                + "      from (SELECT t.DEPARTMENT_NAME, substr(t.STOP_END_D, 1, 7) calendar, sum(t.STOP_HOURS) stop_hours\n"
                + "            FROM SGMC.V_MC_ZB_EM_LJTJ t\n"
                + "            group by t.DEPARTMENT_NAME, substr(t.STOP_END_D, 1, 7)\n"
                + "            order by calendar)\n"
                + "      where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "        and calendar >= to_char(current date - 12 month, 'yyyy-mm'))\n"
                + " where department_name = '"+typeName+"' ";
        return queryDataService.query(sql);
    }

    @Override
    public Object zlYljtjyygc(String typeName) {
        String sql = "select *\n"
                + " from (select decode(department_name, '顺冷', '顺义冷轧', department_name)as department_name, calendar, stop_type, stop_hours\n"
                + "      from (SELECT t.DEPARTMENT_NAME, substr(t.STOP_END_D, 1, 7) calendar, t.STOP_TYPE, sum(t.STOP_HOURS) stop_hours\n"
                + "            FROM SGMC.V_MC_ZB_EM_LJTJ t\n"
                + "            group by t.DEPARTMENT_NAME, substr(t.STOP_END_D, 1, 7), t.STOP_TYPE\n"
                + "            order by stop_hours)\n"
                + "      where calendar = to_char(current date - 1, 'yyyy-mm'))\n"
                + " where department_name = '"+typeName+"' ";
        return queryDataService.query(sql);
    }


    @Override
    public Object mxGlyljtjsj() {
        String sql = " select '系列', department_name, stop_hours, work_area_name\n"
                + " from (select department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "      FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "      WHERE department_name like '%炼铁%'\n"
                + "        and WORK_AREA_NAME not like '%烧结%'\n"
                + "        and WORK_AREA_NAME not like '%球团%'\n"
                + "        and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "      group by department_name, work_area_name--1炼铁\n"
                + "      union all\n"
                + "      select '烧结'department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "      FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "      WHERE WORK_AREA_NAME like '%烧结%'\n"
                + "        and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "      group by department_name, work_area_name--2烧结\n"
                + "      union all\n"
                + "      select '球团'department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "      FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "      WHERE WORK_AREA_NAME like '%球团%'\n"
                + "        and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "      group by department_name, work_area_name--3球团\n"
                + "      union all\n"
                + "      select '智新一区'department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "      FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "      WHERE WORK_AREA_NAME = '一作业区'\n"
                + "        and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "      group by work_area_name--4\n"
                + "      union all\n"
                + "      select '智新二区'department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "      FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "      WHERE WORK_AREA_NAME = '二作业区'\n"
                + "        and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "      group by work_area_name--5\n"
                + "      union all\n"
                + "      select '智新三区'department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "      FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "      WHERE WORK_AREA_NAME = '三作业区'\n"
                + "        and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "      group by work_area_name--6\n"
                + "      union all\n"
                + "      select '酸洗'department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "      FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "      WHERE WORK_AREA_NAME like '%酸洗%'\n"
                + "        and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "      group by work_area_name--酸洗7\n"
                + "      union all\n"
                + "      select '一热轧'department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "      FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "      WHERE WORK_AREA_NAME like '%一热轧%'\n"
                + "        and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "      group by work_area_name--8\n"
                + "      union all\n"
                + "      select '二热轧'department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "      FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "      WHERE WORK_AREA_NAME like '%二热轧%'\n"
                + "        and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "      group by work_area_name--9\n"
                + "      union all\n"
                + "      select '一炼钢'department_name, sum(stop_hours) as stop_hours, '一炼钢作业区'work_area_name\n"
                + "      FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "      WHERE WORK_AREA_NAME like '%一炼钢%'\n"
                + "        and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "      group by department_name--10\n"
                + "      union all\n"
                + "      select '二炼钢'department_name, sum(stop_hours) as stop_hours, '二炼钢作业区'work_area_name\n"
                + "      FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "      WHERE WORK_AREA_NAME like '%二炼钢%'\n"
                + "        and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "      group by department_name--11\n"
                + "      union all\n"
                + "      select '顺义冷轧'department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "      FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "      WHERE WORK_AREA_NAME like '%酸轧%'\n"
                + "        and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "      group by work_area_name)\n"
                + " order by stop_hours ";
        return queryDataService.query(sql);
    }

    @Override
    public Object mxTjsjqsd(String typeName) {
        String sql = "select *\n"
                + "from ((select department_name, stop_hours, calendar\n"
                + "       from (select '炼铁'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE department_name like '%炼铁%'\n"
                + "               and WORK_AREA_NAME not like '%烧结%'\n"
                + "               and WORK_AREA_NAME not like '%球团%'\n"
                + "             group by substr(STOP_END_D, 1, 10)\n"
                + "             order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '烧结'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%烧结%'\n"
                + "             group by substr(STOP_END_D, 1, 10)\n"
                + "             order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '球团'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%球团%'\n"
                + "             group by substr(STOP_END_D, 1, 10)\n"
                + "             order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '智新一区'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME = '一作业区'\n"
                + "             group by substr(STOP_END_D, 1, 10)\n"
                + "             order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '智新二区'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME = '二作业区'\n"
                + "             group by substr(STOP_END_D, 1, 10)\n"
                + "             order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '智新三区'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME = '三作业区'\n"
                + "             group by substr(STOP_END_D, 1, 10)\n"
                + "             order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '酸洗'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%酸洗%'\n"
                + "             group by substr(STOP_END_D, 1, 10)\n"
                + "             order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '一热轧'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%一热轧%'\n"
                + "             group by substr(STOP_END_D, 1, 10)\n"
                + "             order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '二热轧'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%二热轧%'\n"
                + "             group by substr(STOP_END_D, 1, 10)\n"
                + "             order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '一炼钢'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%一炼钢%'\n"
                + "             group by substr(STOP_END_D, 1, 10)\n"
                + "             order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '二炼钢'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%二炼钢%'\n"
                + "             group by substr(STOP_END_D, 1, 10)\n"
                + "             order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '顺义冷轧'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%酸轧%'\n"
                + "             group by substr(STOP_END_D, 1, 10)\n"
                + "             order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar))\n"
                + " where department_name = '"+typeName+"' "
                + "order by calendar ";
        return queryDataService.query(sql);
    }

    @Override
    public Object mxTjsjqsm(String typeName) {
        String sql = " select *\n"
                + "from ((select department_name, stop_hours, calendar\n"
                + "       from (select '炼铁'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE department_name like '%炼铁%'\n"
                + "               and WORK_AREA_NAME not like '%烧结%'\n"
                + "               and WORK_AREA_NAME not like '%球团%'\n"
                + "             group by substr(STOP_END_D, 1, 7)\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '烧结'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%烧结%'\n"
                + "             group by substr(STOP_END_D, 1, 7)\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '球团'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%球团%'\n"
                + "             group by substr(STOP_END_D, 1, 7)\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '智新一区'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME = '一作业区'\n"
                + "             group by substr(STOP_END_D, 1, 7)\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '智新二区'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME = '二作业区'\n"
                + "             group by substr(STOP_END_D, 1, 7)\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '智新三区'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME = '三作业区'\n"
                + "             group by substr(STOP_END_D, 1, 7)\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '酸洗'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%酸洗%'\n"
                + "             group by substr(STOP_END_D, 1, 7)\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '一热轧'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%一热轧%'\n"
                + "             group by substr(STOP_END_D, 1, 7)\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '二热轧'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%二热轧%'\n"
                + "             group by substr(STOP_END_D, 1, 7)\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '一炼钢'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%一炼钢%'\n"
                + "             group by substr(STOP_END_D, 1, 7)\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '二炼钢'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%二炼钢%'\n"
                + "             group by substr(STOP_END_D, 1, 7)\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (select '顺义冷轧'department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%酸轧%'\n"
                + "             group by substr(STOP_END_D, 1, 7)\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar))\n"
                + " where department_name = '"+typeName+"' "
                + "order by calendar ";
        return queryDataService.query(sql);
    }

    @Override
    public Object mxYljtjyygc(String typeName) {

        String sql = " select *\n"
                + " from ((select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (select '炼铁'department_name, sum(stop_hours) as stop_hours, stop_type, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE department_name like '%炼铁%'\n"
                + "               and WORK_AREA_NAME not like '%烧结%'\n"
                + "               and WORK_AREA_NAME not like '%球团%'\n"
                + "             group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (select '烧结'department_name, sum(stop_hours) as stop_hours, stop_type, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%烧结%'\n"
                + "             group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (select '球团'department_name, sum(stop_hours) as stop_hours, stop_type, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%球团%'\n"
                + "             group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (select '智新一区'department_name, sum(stop_hours) as stop_hours, stop_type, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME = '一作业区'\n"
                + "             group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (select '智新二区'department_name, sum(stop_hours) as stop_hours, stop_type, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME = '二作业区'\n"
                + "             group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (select '智新三区'department_name, sum(stop_hours) as stop_hours, stop_type, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME = '三作业区'\n"
                + "             group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (select '酸洗'department_name, sum(stop_hours) as stop_hours, stop_type, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%酸洗%'\n"
                + "             group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (select '一热轧'department_name, sum(stop_hours) as stop_hours, stop_type, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%一热轧%'\n"
                + "             group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (select '二热轧'department_name, sum(stop_hours) as stop_hours, stop_type, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%二热轧%'\n"
                + "             group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (select '一炼钢'department_name, sum(stop_hours) as stop_hours, stop_type, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%一炼钢%'\n"
                + "             group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (select '二炼钢'department_name, sum(stop_hours) as stop_hours, stop_type, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%二炼钢%'\n"
                + "             group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (select '顺义冷轧'department_name, sum(stop_hours) as stop_hours, stop_type, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE WORK_AREA_NAME like '%酸轧%'\n"
                + "             group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar))\n"
                + " where department_name = '"+typeName+"' "
                + "  and calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + " order by calendar ";
        return queryDataService.query(sql);
    }

    @Override
    public Object fjhtjGlyljtjsj() {
        String sql = " select '系列', department_name, stop_hours, work_area_name\n"
                + "from (\n"
                + "         select department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "         FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "         WHERE department_name like '%炼铁%'\n"
                + "           and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "           and WORK_AREA_NAME not like '%烧结%'\n"
                + "           and WORK_AREA_NAME not like '%球团%'\n"
                + "           and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "         group by department_name, work_area_name--1炼铁\n"
                + "         union all\n"
                + "         select '烧结' department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "         FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "         WHERE WORK_AREA_NAME like '%烧结%'\n"
                + "           and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "           and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "         group by department_name, work_area_name--2烧结\n"
                + "         union all\n"
                + "         select '球团' department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "         FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "         WHERE WORK_AREA_NAME like '%球团%'\n"
                + "           and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "           and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "         group by department_name, work_area_name--3球团\n"
                + "         union all\n"
                + "         select '智新一区' department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "         FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "         WHERE WORK_AREA_NAME = '一作业区'\n"
                + "           and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "           and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "         group by work_area_name--4\n"
                + "         union all\n"
                + "         select '智新二区' department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "         FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "         WHERE WORK_AREA_NAME = '二作业区'\n"
                + "           and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "           and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "         group by work_area_name--5\n"
                + "         union all\n"
                + "         select '智新三区' department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "         FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "         WHERE WORK_AREA_NAME = '三作业区'\n"
                + "           and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "           and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "         group by work_area_name--6\n"
                + "         union all\n"
                + "         select '酸洗' department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "         FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "         WHERE WORK_AREA_NAME like '%酸洗%'\n"
                + "           and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "           and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "         group by work_area_name--酸洗7\n"
                + "         union all\n"
                + "         select '一热轧' department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "         FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "         WHERE WORK_AREA_NAME like '%一热轧%'\n"
                + "           and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "           and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "         group by work_area_name--8\n"
                + "         union all\n"
                + "         select '二热轧' department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "         FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "         WHERE WORK_AREA_NAME like '%二热轧%'\n"
                + "           and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "           and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "         group by work_area_name--9\n"
                + "         union all\n"
                + "         select '一炼钢' department_name, sum(stop_hours) as stop_hours, '一炼钢作业区' work_area_name\n"
                + "         FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "         WHERE WORK_AREA_NAME like '%一炼钢%'\n"
                + "           and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "           and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "         group by department_name--10\n"
                + "         union all\n"
                + "         select '二炼钢' department_name, sum(stop_hours) as stop_hours, '二炼钢作业区' work_area_name\n"
                + "         FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "         WHERE WORK_AREA_NAME like '%二炼钢%'\n"
                + "           and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "           and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "         group by department_name--11\n"
                + "         union all\n"
                + "         select '顺义冷轧' department_name, sum(stop_hours) as stop_hours, work_area_name\n"
                + "         FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "         WHERE WORK_AREA_NAME like '%酸轧%'\n"
                + "           and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "\n"
                + "           and stop_begin_d >= to_char(CURRENT DATE - 1, 'yyyy-mm')\n"
                + "         group by work_area_name)\n"
                + "order by stop_hours";
        return queryDataService.query(sql);
    }

    @Override
    public Object fjhtjTjsjqsd(String typeName) {

        String sql = " \n"
                + "\n"
                + "select *\n"
                + "from ((select department_name, stop_hours, calendar\n"
                + "       from (select '炼铁' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE department_name like '%炼铁%'\n"
                + "               and WORK_AREA_NAME not like '%烧结%'\n"
                + "               and WORK_AREA_NAME not like '%球团%'\n"
                + "               and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "             group by substr(STOP_END_D, 1, 10)\n"
                + "             order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '烧结' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%烧结%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 10)\n"
                + "                order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '球团' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%球团%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 10)\n"
                + "                order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '智新一区' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME = '一作业区'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 10)\n"
                + "                order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '智新二区' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME = '二作业区'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 10)\n"
                + "                order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '智新三区' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME = '三作业区'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 10)\n"
                + "                order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '酸洗' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%酸洗%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 10)\n"
                + "                order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '一热轧' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%一热轧%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 10)\n"
                + "                order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '二热轧' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%二热轧%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 10)\n"
                + "                order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '一炼钢' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%一炼钢%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 10)\n"
                + "                order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '二炼钢' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%二炼钢%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 10)\n"
                + "                order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '顺义冷轧' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 10) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%酸轧%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 10)\n"
                + "                order by substr(STOP_END_D, 1, 10))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm-dd')\n"
                + "         and calendar >= to_char(current date - 30, 'yyyy-mm-dd')\n"
                + "       order by calendar))\n"
                + "where department_name = '"+typeName+"'\n"
                + "order by calendar";
        return queryDataService.query(sql);
    }

    @Override
    public Object fjhtjTjsjqsm(String typeName) {

        String sql = " select *\n"
                + "from ((select department_name, stop_hours, calendar\n"
                + "       from (select '炼铁' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE department_name like '%炼铁%'\n"
                + "               and WORK_AREA_NAME not like '%烧结%'\n"
                + "               and WORK_AREA_NAME not like '%球团%'\n"
                + "               and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "             group by substr(STOP_END_D, 1, 7)\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '烧结' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%烧结%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7)\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '球团' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%球团%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7)\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '智新一区' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME = '一作业区'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7)\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '智新二区' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME = '二作业区'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7)\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '智新三区' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME = '三作业区'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7)\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '酸洗' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%酸洗%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7)\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '一热轧' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%一热轧%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7)\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '二热轧' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%二热轧%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7)\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '一炼钢' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%一炼钢%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7)\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '二炼钢' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%二炼钢%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7)\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, stop_hours, calendar\n"
                + "       from (\n"
                + "                select '顺义冷轧' department_name, sum(stop_hours) as stop_hours, substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%酸轧%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7)\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar <= to_char(current date - 1, 'yyyy-mm')\n"
                + "         and calendar >= to_char(current date - 12 month, 'yyyy-mm')\n"
                + "       order by calendar))\n"
                + "where department_name = '"+typeName+"'\n"
                + "order by calendar";


        return queryDataService.query(sql);
    }

    @Override
    public Object fjhtjYljtjyygc(String typeName) {

        String sql = "select *\n"
                + "from ((select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (select '炼铁' department_name, sum(stop_hours) as stop_hours, stop_type, substr(STOP_END_D, 1, 7) calendar\n"
                + "             FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "             WHERE department_name like '%炼铁%'\n"
                + "               and WORK_AREA_NAME not like '%烧结%'\n"
                + "               and WORK_AREA_NAME not like '%球团%'\n"
                + "               and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "             group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "             order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (\n"
                + "                select '烧结' department_name, sum(stop_hours) as stop_hours, stop_type, substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%烧结%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (\n"
                + "                select '球团' department_name, sum(stop_hours) as stop_hours, stop_type, substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%球团%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (\n"
                + "                select '智新一区'                   department_name,\n"
                + "                       sum(stop_hours) as       stop_hours,\n"
                + "                       stop_type,\n"
                + "                       substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME = '一作业区'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (\n"
                + "                select '智新二区'                   department_name,\n"
                + "                       sum(stop_hours) as       stop_hours,\n"
                + "                       stop_type,\n"
                + "                       substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME = '二作业区'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (\n"
                + "                select '智新三区'                   department_name,\n"
                + "                       sum(stop_hours) as       stop_hours,\n"
                + "                       stop_type,\n"
                + "                       substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME = '三作业区'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (\n"
                + "                select '酸洗' department_name, sum(stop_hours) as stop_hours, stop_type, substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%酸洗%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (\n"
                + "                select '一热轧'                    department_name,\n"
                + "                       sum(stop_hours) as       stop_hours,\n"
                + "                       stop_type,\n"
                + "                       substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%一热轧%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (\n"
                + "                select '二热轧'                    department_name,\n"
                + "                       sum(stop_hours) as       stop_hours,\n"
                + "                       stop_type,\n"
                + "                       substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%二热轧%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (\n"
                + "                select '一炼钢'                    department_name,\n"
                + "                       sum(stop_hours) as       stop_hours,\n"
                + "                       stop_type,\n"
                + "                       substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%一炼钢%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (\n"
                + "                select '二炼钢'                    department_name,\n"
                + "                       sum(stop_hours) as       stop_hours,\n"
                + "                       stop_type,\n"
                + "                       substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%二炼钢%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar)\n"
                + "      union all\n"
                + "      (select department_name, sum(stop_hours) stop_hours, stop_type, calendar\n"
                + "       from (\n"
                + "                select '顺义冷轧'                   department_name,\n"
                + "                       sum(stop_hours) as       stop_hours,\n"
                + "                       stop_type,\n"
                + "                       substr(STOP_END_D, 1, 7) calendar\n"
                + "                FROM SGMC.V_MC_ZB_EM_LJTJ\n"
                + "                WHERE WORK_AREA_NAME like '%酸轧%'\n"
                + "                  and stop_type not in ('设备计划检修', '生产计划停机', '换辊')\n"
                + "                group by substr(STOP_END_D, 1, 7), stop_type\n"
                + "                order by substr(STOP_END_D, 1, 7))\n"
                + "       where calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "       group by stop_type, department_name, calendar\n"
                + "       order by calendar))\n"
                + "where department_name = '"+typeName+"'\n"
                + "  and calendar = to_char(current date - 1, 'yyyy-mm')\n"
                + "order by calendar";
        return queryDataService.query(sql);
    }

    @Override
    public Object jzyxzt(String typeCode) {

        String sqlCondition = getJzyxztSqlCondition(typeCode);
        if (null == sqlCondition) {
            return null;
        }

        String sql = " select department_name,line_name,stop_begin_time, stop_state \n"
                + " from sgmc.V_MC_ZB_EM_SSZT \n"
                + " where 1=1  and  " + sqlCondition
                + " order by stop_state  ";
        return queryDataService.query(sql);
    }

    @Override
    public Object wxcbGdwxlfy() {

        String sql = " select calendar, decode(zb_name, '冷轧', '顺冷', zb_name)as zb_name, sum(zb_value) zb_value\n"
                + " from (select t.CALENDAR, left(ZB_NAME, 4) zb_name, t.ZB_VALUE\n"
                + "      from sgmc.V_MC_ZB_EM_WXCB t\n"
                + "      where t.CALENDAR = to_char(current date - 1 month, 'yyyy-mm'))\n"
                + " group by CALENDAR, ZB_NAME\n"
                + " order by ZB_VALUE ";
        return queryDataService.query(sql);
    }

    @Override
    public Object wxcbWxfyydqs(String typeName) {

        String sql = " select calendar, sum(zb_value) as zb_value, '维修费' "
                + " from sgmc.V_MC_ZB_EM_WXCB "
                + " where replace(zb_name, '冷轧', '顺义冷轧') like '%"+typeName+"%' "
                + "  and calendar >= to_char(add_months(sysdate, -7), 'yyyy-mm') "
                + "  and calendar <= to_char(add_months(sysdate, -1), 'yyyy-mm') "
                + " group by calendar "
                + " order by calendar ";
        return queryDataService.query(sql);
    }

    @Override
    public Object wxcbXlfygc(String typeName) {

        String sql = " select calendar,\n"
                + "       zb_code,\n"
                + "       SUBSTR(ZB_NAME, INSTR(ZB_NAME, '_', 1) + 1, INSTR(ZB_NAME, '_', -1) - INSTR(ZB_NAME, '_') - 1) as zb_name,\n"
                + "       zb_value,\n"
                + "       unit_name\n"
                + " from (select calendar, zb_code, zb_name, zb_value, unit_name\n"
                + "      from (select calendar, zb_code, replace(zb_name, '冷轧', '顺义冷轧')as zb_name, zb_value, unit_name\n"
                + "            from sgmc.V_MC_ZB_EM_WXCB\n"
                + "            where CALENDAR = to_char(current date - 1 month, 'yyyy-mm')\n"
                + "            order by CALENDAR desc)\n"
                + "      order by zb_value)\n"
                + " where zb_name like '%"+typeName+"%' ";
        return queryDataService.query(sql);
    }

    private String getJzyxztSqlCondition(String typeCode) {

        /*
        switch (typeCode) {
            case "qt":
                return "球团";
            case "sj":
                return "烧结";
            case "lt":
                return "炼铁";
            case "lg":
                return "炼钢";
            case "rz":
                return "热轧";
            case "zx":
                return "智新";
            case "sl":
                return "顺义冷轧";
            default:
                return null;
        }
        */

        String typeName;
        switch (typeCode) {
            case "qt":
                typeName = "球团";
                break;
            case "sj":
                typeName = "烧结";
                break;
            case "lt":
//                typeName = "炼铁";
                typeName = "高炉";
                break;
            case "lg":
                typeName = "炼钢";
                break;
            case "rz":
                typeName = "热轧";
                break;
            case "zx":
                typeName = "智新";
                break;
            case "sl":
                typeName = "顺义冷轧";
                break;
            default:
                return null;
        }

        if ("qt".equals(typeCode) || "sj".equals(typeCode) || "lt".equals(typeCode)) {
            return " line_name like '%"+typeName+"%' ";
        } else{
            return " decode(department_name,'顺冷','顺义冷轧',department_name)  = '"+typeName+"'";
        }

    }
}
